name: alacritty
version: '0.4.2-dev'
summary: Modern, GPU accelerated terminal emulator
description: |
  Alacritty is a terminal emulator with a strong focus on simplicity and
  performance. With such a strong focus on performance, included features are
  carefully considered and you can always expect Alacritty to be blazingly fast.
  By making sane choices for defaults, Alacritty requires no additional setup.
  However, it does allow [configuration](#configuration) of many aspects of the
  terminal.

  The software is considered to be at a **beta** level of readiness -- there are
  a few missing features and bugs to be fixed, but it is already used by many as
  a daily driver.
icon: extra/logo/alacritty-term.svg
grade: stable
confinement: classic
parts:
  alacritty:
    plugin: rust
    source: .
    build-packages: [libfreetype6-dev, libfontconfig1-dev, cmake]
  desktop:
    plugin: dump
    source: .
    stage:
      - extra/linux/alacritty.desktop
apps:
  alacritty:
    command: env XDG_RUNTIME_DIR= XDG_CONFIG_HOME=$SNAP_USER_DATA XDG_DATA_DIRS=$SNAP_DATA PATH=$SNAP/bin:$PATH SNAP= alacritty
    desktop: alacritty.desktop
