name: alacritty
version: '0.2.8' # just for humans, typically '1.2+git' or '1.3.2'
summary: Modern, GPU accelerated terminal emulator
description: |
  Alacritty is the fastest terminal emulator in existence. Using the GPU
  for rendering enables optimizations that simply aren't possible in
  other emulators.

  Alacritty is focused on simplicity and performance. The performance
  goal means it should be faster than any other terminal emulator
  available. The simplicity goal means that it doesn't have features
  such as tabs or splits (which can be better provided by a window
  manager or terminal multiplexer) nor niceties like a GUI config editor.

  The software is considered to be at an alpha level of readiness—there
  are missing features and bugs to be fixed, but it is already used by
  many as a daily driver.
grade: stable
confinement: classic
parts:
  alacritty:
    plugin: rust
    source: .
    stage-packages: [xclip]
    build-packages: [libfreetype6-dev, libfontconfig1-dev, cmake]
  desktop:
    plugin: dump
    source: .
    stage:
      - alacritty.desktop
apps:
  alacritty:
    command: env XDG_RUNTIME_DIR= XDG_CONFIG_HOME=$SNAP_USER_DATA XDG_DATA_DIRS=$SNAP_DATA PATH=$SNAP/bin:$PATH SNAP= alacritty
    desktop: alacritty.desktop
