name: alacritty # you probably want to 'snapcraft register <name>'
version: '0.2.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Modern, GPU accelerated terminal emulator # 79 char long summary
description: |
  Modern, GPU accelerated terminal emulator
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots
parts:
  alacritty:
    plugin: rust
    source: .
    stage-packages: [xclip]
    build-packages: [libfreetype6-dev, libfontconfig1-dev, cmake]
  desktop:
    plugin: dump
    source: .
    stage:
      - alacritty.desktop
apps:
  alacritty:
    command: env XDG_RUNTIME_DIR= XDG_CONFIG_HOME=$SNAP_USER_DATA XDG_DATA_DIRS=$SNAP_DATA PATH=$SNAP/bin:$PATH SNAP= alacritty
    desktop: alacritty.desktop
